import os
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from torch import optim
import tqdm
import matplotlib.pyplot as plt


##### changer l'ordre  des k ==> k1,t0,k2,t0...kn,t0;k1,t1,k2,t1...kn,t1 etc#########


# check if cuda available ==> log
command = torch.cuda.is_available()
#os.system(f'{command}')

######### The data generated by the shell model #######
PATH = r"/Odyssey/private/s26calme/"
path_data = PATH + "data.dat"

data =  np.loadtxt(path_data)
Nmax = np.shape(data)[0]
debut = int(0.1*Nmax)
Data_shell = data[debut:Nmax,::2] # on garde que la partie réelle de chaque shell

Npts = np.shape(Data_shell)[0] # nombre de pas dans le temps



def filter_mode(X,mode_min:int,mode_max:int,t_min:int,ratio:float,seed):
    
    np.random.seed(seed=seed)
    X_subset = np.copy(X)
    X_subset[:,0:mode_min] = None #enlève les modes inférieurs à mode_min
    X_subset[0:t_min,:] = None #enlève la phase de stabilisation
    nb_column = np.shape(X_subset)[1]
    nb_line = np.shape(X_subset)[0]
    X_filtered = np.copy(X_subset)
    X_posx = []
    X_posy = []
    X_value = []
    X_dataset = []

    var_mode = [np.var(X[:,j]) for j in range(nb_column)]
    std_mode = [np.std(X[:,j]) for j in range(nb_column)]
    mean_mode = [np.mean(X[:,j]) for j in range(nb_column)]

    for j in range(mode_min,mode_max):
        for i in range(t_min,nb_line):
            if (np.random.random()<=ratio):
                X_filtered[i,j] = X_subset[i,j]
                X_posx.append(j)
                X_posy.append(i)
                X_value.append((X_subset[i,j]-mean_mode[j])/std_mode[j]) # centré réduit

            else:
                X_filtered[i,j] = None
    
    pourcentage_filtered = nb_line*ratio/nb_line*100
    X_dataset.append(X_posx)
    X_dataset.append(X_posy)
    X_dataset.append(X_value)
    return X_filtered,var_mode,std_mode,pourcentage_filtered,X_dataset,mean_mode


def reduced_center(X,mean,std):
    for k in range(X.shape[1]):
        X[:,k]= (X[:,k]-mean[k])/std[k]
    return X

# retourne un dataset pour plot , var,std,et mean pour chaque mode et les colocation point centré réduit
Data_filtered ,Var_mode,Std_mode,perc,Data_train,mean = filter_mode(Data_shell,4,10,0,0.001,123456)


Data_shell = reduced_center(Data_shell,mean,Std_mode) # centré réduit tous les modes 
Data_ic = Data_shell[0,:] # prends tous le spoints en t=0
Data_bc = Data_shell[:,0:4] # prends tous les points de bords (shell allant de 0->3 avec 3 shell de forçage)

print("Moyenne de l'ensemble des mode",np.mean(Data_shell))
print("std de tous les modes ", np.std(Data_shell))


#########  carateristics of the shell model ############

k0 = 0.125    # largest scale
lmb = 2.0     #ratio between consecutive scales
eps =  0.5     # for the NL coefficients
nu = 1.e-7     # vicosité
nb_shell = 22 
dt = 1
############ parameters for the PINN ############

# nb of shells selected for training the PINN on collocatin point
k_min_collocation = 4 
k_max_collocation = 10 

#nb of shells for training on boundary conditions
k_bc_min = 0
k_bc_max = 4 

# k_min et k_max sur l'ensemble des shells à reconstituter 
k_min = min(k_min_collocation,k_bc_min)
k_max = max(k_bc_max,k_max_collocation)

# list of coefficient kn for all shells
K = [k0*lmb**i for i in range(k_min,k_max)]


class GOY_PINN(nn.Module):

    def __init__(self,n_input,n_output,n_hidden,n_layers):
        super().__init__()

        activation = nn.Tanh
        self.input_layer = nn.Sequential(*[
                                    nn.Linear(n_input, n_hidden),
                                    activation()]).to(device)

        self.hidden_layers = nn.Sequential(*[
                        nn.Sequential(*[
                            nn.Linear(n_hidden, n_hidden),
                            activation()]) for _ in range(n_layers-1)]).to(device)

        self.output_layer = nn.Linear(n_hidden, n_output).to(device)

    def forward(self,x):

        x=self.input_layer(x)
        x=self.hidden_layers(x)
        x=self.output_layer(x)

        return x


def initial_conditions(X_ic,k_initial,t_initial):
    return X_ic[t_initial,k_initial]

# Dirichlet boundary condition
def boundary_conditions(X_bc,k_boundary,t_boundary):
    u_boundary = X_bc[t_boundary,k_boundary]
    return u_boundary

class initials_variables_data(torch.utils.data.Dataset):
    def __init__(self,X_ic,nbr_initial_t,k_min,k_max): # conditions initiales à t=0 et k sur l'ensemble des k
        
        #initialise the variables
        self.k_min = k_min
        self.k_max = k_max
        self.X_ic = X_ic[self.k_min:self.k_max]  # select only the shells between k_min and k_max
        self.nbr_initial_t = nbr_initial_t
        
        self.x_initial = np.array([k for k in range(k_min,k_max)],dtype="float32") # shells selected for initial conditions
        self.t_initial = np.array([0 for _ in range(self.nbr_initial_t)],dtype="float32")  # 0 since the initial condition is defined for t=0
        
        # transform data and grid to the shape (k,t,u)
        self.tensor_data_ic = torch.tensor(self.X_ic, dtype=torch.float32)
        self.grille = np.meshgrid(self.x_initial,self.t_initial)
        self.grille = torch.tensor(self.grille, dtype=torch.float32).T.view(np.shape(self.x_initial)[0]*np.shape(self.t_initial)[0],2)
        
        self.tensor_data = torch.ones((np.shape(self.x_initial)[0]*np.shape(self.t_initial)[0],3), dtype=torch.float32)
        self.tensor_data[:,0:2] = self.grille
        self.tensor_data[:,2] = self.tensor_data_ic
        
    def __len__(self):
        #return the lenght of the dataset
        return self.x_initial.shape[0]*self.t_initial.shape[0]

    def __getitem__(self,idx):

        return self.tensor_data[idx,0], self.tensor_data[idx,1], self.tensor_data[idx,2]  #return the x and t values of the grid and value of X for the initial condition



class boundary_variables_data(torch.utils.data.Dataset):
    def __init__(self,X_boundary):
        
        
        self.X_boundary = X_boundary[0:Npts,:]
        self.nb_k = np.shape(X_boundary)[1]
        self.nb_t = np.shape(X_boundary)[0]
        self.tensor_data_bc = torch.ones((self.nb_k*self.nb_t,3), dtype=torch.float32) #columns: k, t, u
        
        # trouver solution tq pour tout t, t!=0
        for k in range(self.nb_k*self.nb_t): # data ordered as (k,t,u) in the grid
            self.tensor_data_bc[k,0],self.tensor_data_bc[k,1],self.tensor_data_bc[k,2] = k//(self.nb_t),k%(self.nb_t),self.X_boundary[k%self.nb_t,k//self.nb_t]
        # for k in range(self.nb_k):
        #     print(self.tensor_data_bc[k*(self.nb_t-3):k*(self.nb_t+3)]) 
       
    def __len__(self):
        #return the lenght of the dataset
        return self.nb_k*self.nb_t
    def __getitem__(self,idx):

        # return the element in that index (k,t,u)[idx] 
        return self.tensor_data_bc[idx,0],self.tensor_data_bc[idx,1],self.tensor_data_bc[idx,2]

class colocations_variables_data(torch.utils.data.Dataset):
    def __init__(self,X_Data_train):
        #initialise the variables

        self.X_Data_train = X_Data_train
        self.nb_colocation_pnt = len(self.X_Data_train[1])
        #colocation points aranged as (k,t,u) in the grid
        self.tensor_data_colocation = torch.tensor(self.X_Data_train, dtype=torch.float32).T.view(self.nb_colocation_pnt,3)


    def __len__(self):
        #return the lenght of the dataset
        return self.nb_colocation_pnt
   

    def __getitem__(self,idx):

        # return the element in that index (k,t,u)[idx]
        return torch.self.tensor_data_colocation[idx,0],self.tensor_data_colocation[idx,1].item,self.tensor_data_colocation[idx,2].item() #float(self.X_Data_train[idx][0]),float(self.X_Data_train[idx][1]) ,torch.tensor(self.X_Data_train[idx][2])   #return the x and t values of the grid and value of X for the physics loss
        #return self.x[j],self.t[i]  # This class only returns the x and t values of the grid not the velocity


class grid_data(torch.utils.data.Dataset):
    def __init__(self,k_min,k_max,t_min,t_max):
        #initialise the variables
        self.k_min = k_min
        self.k_max = k_max
        self.t_min = t_min
        self.t_max = t_max
        self.x = np.array([k for k in range(k_min,k_max)],dtype="float32")
        self.t = np.array([t for t in range(t_min,t_max)],dtype="float32")
        self.x, self.t = torch.tensor(self.x, dtype=torch.float32), torch.tensor(self.t, dtype=torch.float32)
        self.grille = torch.ones((k_max-k_min)*(t_max-t_min),2, dtype=torch.float32)
        for k in range((k_max-k_min)*(t_max-t_min)):
            i = k%(t_max-t_min)
            j = k//(t_max-t_min)
            self.grille[k,0],self.grille[k,1] = self.x[j],self.t[i]

        self.N_k = np.shape(self.x)[0] 
        self.N_t = np.shape(self.t)[0]

    def __len__(self):
        #return the lenght of the dataset
        return self.N_t*self.N_k

    def __getitem__(self,idx):
        return self.grille[idx,0],self.grille[idx,1]  # This class only returns the x and t values of the grid not the velocity

class Train_PINN():

    def __init__(self,learning_rate,nbr_iteration,w_1,w_2,w_3,w_4):
        self.learning_rate = learning_rate
        self.nbr_iteration = nbr_iteration
        self.w_1 = w_1
        self.w_2 = w_2
        self.w_3 = w_3
        self.w_4 = w_4
        self.optimizer = torch.optim.Adam(model.parameters(),lr = self.learning_rate)
        
    def train(self):

        loss = np.zeros((self.nbr_iteration,1))
        loss_physics_tracker = np.zeros((self.nbr_iteration,1))
        loss_colocation_tracker = np.zeros((self.nbr_iteration,1))
        loss_boundary_conditions_tracker = np.zeros((self.nbr_iteration,1))
        loss_initial_conditions_tracker = np.zeros((self.nbr_iteration,1))

        for iteration in tqdm.tqdm(range(self.nbr_iteration)):
            self.optimizer.zero_grad()

            #initial conditions Loss
            
            initial_train_data = initial_train_dataset.tensor_data.to(device) #torch.tensor(initial_rows, dtype=torch.float32)
            u_pd_ini = model(initial_train_data[:, 0:2])#.to(device)
            u_exa_ini = initial_train_data[:,2:3]
            loss_initital_conditions = self.w_1*torch.mean((u_pd_ini-u_exa_ini)**2)#.to(device)

            #Boundary conditions Loss
            boundary_train_data = boundary_train_dataset.tensor_data_bc.to(device)#torch.tensor(boundary_rows, dtype=torch.float32)
            u_pd_bou = model(boundary_train_data[:, 0:2])#.to(device)
            u_exa_bou = boundary_train_data[:,2:3]
            loss_boundary_conditions = self.w_2*torch.mean((u_pd_bou-u_exa_bou)**2)#.to(device)


            
            colocation_train_data = colocation_dataset.tensor_data_colocation.to(device)
            u_pd_colocation = model(colocation_train_data[:,0:2])#.to(device)
            loss_colocation = self.w_3*torch.mean((u_pd_colocation-colocation_train_data[:,2])**2)#.to(device)

            grid_train_data = grid_dataset.grille.requires_grad_(True).to(device)
            u_pd = model(grid_train_data).to(device)
            #a = torch.autograd.grad(u_pd, train_data, torch.ones_like(u_pd), create_graph=True)
            u_t = torch.autograd.grad(u_pd, grid_train_data, torch.ones_like(u_pd), create_graph=True)[0][:,1:2]#.to(device)
    
            # u_x = torch.autograd.grad(u_pd, train_data, torch.ones_like(u_pd), create_graph=True)[0][:,0:1]
            # u_xx = torch.autograd.grad(u_x, train_data, torch.ones_like(u_pd), create_graph=True)[0][:,0:1]
            
            # u_t_split = torch.split(u_t,int(grid_train_data.shape[0]/(k_max-k_min)))
            # tuple_u_t = tuple(k for k in u_t_split)
            # u_t = torch.cat(tuple_u_t,1).to(device)
            
            #u_pd = u_pd.view(int(grid_train_data.shape[0]/(k_max-k_min)),int(k_max-k_min))
            # u_pd_split = torch.split(u_t,int(grid_train_data.shape[0]/(k_max-k_min)))
            # tuple_u_pd = tuple(k for k in u_pd_split)
            # u_pd = torch.cat(tuple_u_pd,1).to(device)         
            u_pd = u_pd.view(k_max-k_min,Npts).T
            u_t = u_t.view(k_max-k_min,Npts).T
            # on veut calculer la loss physique sur le shells où il y a des collocations points
            GOY_physics = torch.zeros(Npts,(k_max-2 - k_min_collocation)).to(device)
            #print(GOY_physics.shape)
            for i in range (k_min_collocation,k_max-2):
                GOY_physics[:,i-k_min_collocation] = u_t[:,i] -K[i]*u_pd[:,i+1]*u_pd[:,i+2] +K[i]*eps/lmb*u_pd[:,i-1]*u_pd[:,i+1] + K[i]*((eps-1)/lmb**2)*u_pd[:,i-2]*u_pd[:,i-1] + nu*K[i]*K[i]*u_pd[:,i] # à confirmer
            loss_physics = self.w_4*torch.mean(GOY_physics**2).to(device)

            #Total Loss
            total_loss = loss_initital_conditions + loss_boundary_conditions + loss_physics + loss_colocation
            total_loss.backward()
            self.optimizer.step()
            loss[iteration]=total_loss.cpu().detach().numpy()
            loss_physics_tracker[iteration] = loss_physics.cpu().detach().numpy()
            loss_colocation_tracker[iteration] = loss_colocation.cpu().detach().numpy()
            loss_boundary_conditions_tracker[iteration] = loss_boundary_conditions.cpu().detach().numpy()
            loss_initial_conditions_tracker[iteration] = loss_initital_conditions.cpu().detach().numpy()
            print(iteration)
            print(total_loss)
            
            
        return loss,loss_physics_tracker,loss_colocation_tracker,loss_boundary_conditions_tracker,loss_initial_conditions_tracker





############ initialization of model ###########
torch.manual_seed(119)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model = GOY_PINN(n_input=2,n_output=1,n_hidden=128,n_layers=8)
model.to(device)


nbr_initial_t = 1     # Only t=0 for defining the initial condition
t_min = 0             
t_max = Npts

############# initialization of dataset for training #################
initial_train_dataset = initials_variables_data(Data_ic,nbr_initial_t,k_min,k_max)
boundary_train_dataset = boundary_variables_data(X_boundary=Data_bc)
colocation_dataset = colocations_variables_data(Data_train)
grid_dataset = grid_data(k_min,k_max,t_min,t_max)
boundary_train_dataset.tensor_data_bc.to(device)
colocation_dataset.tensor_data_colocation.to(device)
grid_dataset.grille.to(device)


def test_loss(Data_train,grille_datatset):

    # grid_train_data = grille_datatset.grille # donne la grille des (k,t)
    # grid_train_data.requires_grad = True # permet d'appliqué grad
    data = Data_train[:,k_min_collocation:k_max]
    grille = [t for t in range(Npts)]
    u = torch.tensor(Data_train[:,k_min:k_max],requires_grad=True) #tensor des U(k,t)  #view(Npts,k_max-k_min)
    #tensor_split = torch.split(tensor_data,k_max-k_min,1)
    u_t = np.copy(Data_train[:,k_min_collocation:k_max])
    for k in range(k_min_collocation,k_max):
        for t in range(0,Npts-1):
            u_t[t,k-k_min_collocation] = (data[t+1,k-k_min_collocation]*np.exp(nu*K[k]*dt)-data[t,k-k_min_collocation])/dt


    u_t = torch.tensor(u_t)
    GOY_physics = torch.zeros(Npts,(k_max - k_min_collocation))
 
    
    for i in range (k_min_collocation,k_max-2):
            GOY_physics[:,i-k_min_collocation] = u_t[:,i-k_min_collocation] -K[i]*u[:,i+1]*u[:,i+2] +K[i]*eps/lmb*u[:,i-1]*u[:,i+1] - K[i]*((eps-1)/lmb**2)*u[:,i-2]*u[:,i-1] + nu*K[i]*K[i]*u[:,i] #deltat =1
            plt.figure()
            plt.plot(grille,GOY_physics[:,i-k_min_collocation].detach().numpy(),label=f'Loss shell{i-k_min_collocation}')
            plt.legend()
            plt.savefig(PATH + f"loss_shell_{i-k_min_collocation}")
    print(torch.max(GOY_physics),torch.min(GOY_physics),torch.std_mean(GOY_physics))
    loss_physics = torch.mean(GOY_physics**2)
    return loss_physics,GOY_physics

#test_loss(Data_train=Data_shell,grille_datatset=grid_dataset)



learning_rate,nbr_iteration,w_1,w_2,w3,w_4 = 0.001,400000,1,1,1,1
t = Train_PINN(learning_rate,nbr_iteration,w_1,w_2,w3,w_4)
Total_loss = t.train()
model.eval().to(device)

U = model(grid_dataset.grille.to(device))
U_split = torch.split(U,Npts)
U = torch.cat(tuple(k for k in U_split),1).to(device)
U = U.cpu().detach().numpy()#.detach().numpy().reshape(t_max-t_min,k_max-k_min)
U_exa = Data_shell[t_min:t_max,k_min:k_max]

square_error = (U-U_exa)**2
rmse = np.sqrt(np.mean(square_error))
print("RMSE:", rmse)



for i in range(U.shape[1]):
    plt.figure()
    plt.plot(U[:,i],label=f'Predicted u{i}')
    plt.plot(U_exa[:,i],label=f'Exact u{i}')
    plt.xlabel('Time')
    plt.ylabel('Velocity')
    plt.legend()
    plt.savefig(PATH + f"prediction_u{i}.png")



#torch.save(model.state_dict(),'/Odyssey/private/s26calme/code_stage/')


plt.figure()
plt.plot(Total_loss[0],label='Total Loss')
plt.plot(Total_loss[1],label='Physics Loss')
plt.plot(Total_loss[2],label='Colocation Loss')
plt.plot(Total_loss[3],label='Boundary Conditions Loss')
plt.plot(Total_loss[4],label='initial Conditions Loss' )  
plt.xlabel('Iterations')
plt.ylabel('Losses')
plt.legend()
plt.savefig(PATH + "losses.png")
