import os
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from torch import optim
import tqdm
import matplotlib.pyplot as plt


##### changer l'ordre  des k ==> k1,t0,k2,t0...kn,t0;k1,t1,k2,t1...kn,t1 etc#########


# check if cuda available ==> log
command = torch.cuda.is_available()
print(command)
#os.system(f'cuda available : {command}')

######### The data generated by the shell model #######
PATH = r"/Odyssey/private/s26calme/code_stage/GOY-main/"
path_data = PATH + "data.dat"

data =  np.loadtxt(path_data)
Data_shell = data[:,::2]
Data_ic = Data_shell[0,:]
Data_bc = Data_shell[:,0:4]
Npts = np.shape(Data_shell)[0]



def filter_mode(X,mode_min:int,mode_max:int,t_min:int,ratio:float,seed):
    
    np.random.seed(seed=seed)
    X_subset = np.copy(X)
    X_subset[:,0:mode_min] = None #enlève les modes inférieurs à mode_min
    X_subset[0:t_min,:] = None #enlève la phase de stabilisation
    nb_column = np.shape(X_subset)[1]
    nb_line = np.shape(X_subset)[0]
    X_filtered = np.copy(X_subset)
    X_posx = []
    X_posy = []
    X_value = []
    X_dataset = []
    for j in range(mode_min,mode_max):
        for i in range(t_min,nb_line):
            if (np.random.random()<=ratio):
                X_filtered[i,j] = X_subset[i,j]
                X_posx.append(j)
                X_posy.append(i)
                X_value.append(X_subset[i,j])

            else:
                X_filtered[i,j] = None
    var_mode = [np.var(X[:,j]) for j in range(nb_column)]
    std_mode = [np.std(X[:,j]) for j in range(nb_column)]
    pourcentage_filtered = nb_line*ratio/nb_line*100
    X_dataset.append(X_posx)
    X_dataset.append(X_posy)
    X_dataset.append(X_value)
    return X_filtered,var_mode,std_mode,pourcentage_filtered,X_dataset

Data_filtered ,Var_mode,Std_mode,perc,Data_train = filter_mode(Data_shell,5,10,int(0.1*100100),0.001,123456)



#########  carateristics of the shell model ############

k0 = 0.125    # largest scale
lmb = 2.0     #ratio between consecutive scales
eps =  0.5     # for the NL coefficients
nu = 1.e-7
nb_shell = 22 

############ parameters for the PINN ############

# nb of shells selected for training the PINN on collocatin point
k_min_collocation = 5
k_max_collocation = 10

#nb of shells for training on boundary conditions
k_bc_min = 0
k_bc_max = 4 

k_min = min(k_min_collocation,k_bc_min)
k_max = max(k_bc_max,k_max_collocation)

# list of coefficient kn for all shells
K = [k0*lmb**i for i in range(k_min,k_max)]


class GOY_PINN(nn.Module):

    def __init__(self,n_input,n_output,n_hidden,n_layers):
        super().__init__()

        activation = nn.Tanh
        self.input_layer = nn.Sequential(*[
                                    nn.Linear(n_input, n_hidden),
                                    activation()])

        self.hidden_layers = nn.Sequential(*[
                        nn.Sequential(*[
                            nn.Linear(n_hidden, n_hidden),
                            activation()]) for _ in range(n_layers-1)])

        self.output_layer = nn.Linear(n_hidden, n_output)

    def forward(self,x):

        x=self.input_layer(x)
        x=self.hidden_layers(x)
        x=self.output_layer(x)

        return x


def initial_conditions(X_ic,k_initial,t_initial):
    return X_ic[t_initial,k_initial]

# Dirichlet boundary condition
def boundary_conditions(X_bc,k_boundary,t_boundary):
    u_boundary = X_bc[t_boundary,k_boundary]
    return u_boundary

class initials_variables_data(torch.utils.data.Dataset):
    def __init__(self,X_ic,nbr_initial_t,k_min,k_max): # conditions initiales à t=0 et k sur l'ensemble des k
        
        #initialise the variables
        self.X_ic = X_ic[k_min:k_max]  # select only the shells between k_min and k_max
        self.nbr_initial_t = nbr_initial_t
        self.k_min = k_min
        self.k_max = k_max
        self.x_initial = np.array([k for k in range(k_min,k_max)],dtype="float32") # shells selected for initial conditions
        self.t_initial = np.array([0 for _ in range(self.nbr_initial_t)],dtype="float32")  # 0 since the initial condition is defined for t=0
        
        # transform data and grid to the shape (k,t,u)
        self.tensor_data_ic = torch.tensor(self.X_ic, dtype=torch.float32)
        self.grille = np.meshgrid(self.x_initial,self.t_initial)
        self.grille = torch.tensor(self.grille, dtype=torch.float32).T.view(np.shape(self.x_initial)[0]*np.shape(self.t_initial)[0],2)
        
        self.tensor_data = torch.ones((np.shape(self.x_initial)[0]*np.shape(self.t_initial)[0],3), dtype=torch.float32)
        self.tensor_data[:,0:2] = self.grille
        self.tensor_data[:,2] = self.tensor_data_ic
        
    def __len__(self):
        #return the lenght of the dataset
        return self.x_initial.shape[0]*self.t_initial.shape[0]

    def __getitem__(self,idx):

        return self.tensor_data[idx,0], self.tensor_data[idx,1], self.tensor_data[idx,2]  #return the x and t values of the grid and value of X for the initial condition



class boundary_variables_data(torch.utils.data.Dataset):
    def __init__(self,X_boundary):
        
        
        self.X_boundary = X_boundary 
        self.nb_k = np.shape(X_boundary)[1]
        self.nb_t = np.shape(X_boundary)[0]
        self.tensor_data_bc = torch.ones((self.nb_k*self.nb_t,3), dtype=torch.float32) #columns: k, t, u
        
        for k in range(self.nb_k*self.nb_t): # data ordered as (k,t,u) in the grid
            self.tensor_data_bc[k,0],self.tensor_data_bc[k,1],self.tensor_data_bc[k,2] = k//self.nb_t,k%self.nb_t,self.X_boundary[(k)%self.nb_t,(k)//self.nb_t] 
    
    def __len__(self):
        #return the lenght of the dataset
        return self.nb_k*self.nb_t
    def __getitem__(self,idx):

        # return the element in that index (k,t,u)[idx] 
        return self.tensor_data_bc[idx,0],self.tensor_data_bc[idx,1],self.tensor_data_bc[idx,2]

class colocations_variables_data(torch.utils.data.Dataset):
    def __init__(self,X_Data_train):
        #initialise the variables

        self.X_Data_train = X_Data_train
        self.nb_colocation_pnt = len(self.X_Data_train[1])
        #colocation points aranged as (k,t,u) in the grid
        self.tensor_data_colocation = torch.tensor(self.X_Data_train, dtype=torch.float32).T.view(self.nb_colocation_pnt,3)


    def __len__(self):
        #return the lenght of the dataset
        return self.nb_colocation_pnt
   

    def __getitem__(self,idx):

        # return the element in that index (k,t,u)[idx]
        return torch.self.tensor_data_colocation[idx,0],self.tensor_data_colocation[idx,1].item,self.tensor_data_colocation[idx,2].item() #float(self.X_Data_train[idx][0]),float(self.X_Data_train[idx][1]) ,torch.tensor(self.X_Data_train[idx][2])   #return the x and t values of the grid and value of X for the physics loss
        #return self.x[j],self.t[i]  # This class only returns the x and t values of the grid not the velocity


class grid_data(torch.utils.data.Dataset):
    def __init__(self,k_min,k_max,t_min,t_max):
        #initialise the variables
        self.k_min = k_min
        self.k_max = k_max
        self.t_min = t_min
        self.t_max = t_max
        self.x = np.array([k for k in range(k_min,k_max)],dtype="float32")
        self.t = np.array([t for t in range(t_min,t_max)],dtype="float32")
        self.x, self.t = torch.tensor(self.x, dtype=torch.float32), torch.tensor(self.t, dtype=torch.float32)
        self.grille = torch.ones((k_max-k_min)*(t_max-t_min),2, dtype=torch.float32)
        for k in range((k_max-k_min)*(t_max-t_min)):
            i = k%(t_max-t_min)
            j = k//(t_max-t_min)
            self.grille[k,0],self.grille[k,1] = self.x[j],self.t[i]

        self.N_k = np.shape(self.x)[0] 
        self.N_t = np.shape(self.t)[0]

    def __len__(self):
        #return the lenght of the dataset
        
        return self.N_t*self.N_k
    # voir comment go through the dataset  et quoi return for the physics loss

    def __getitem__(self,idx):
        # return the element in that index
        # j = (idx)//self.N_k
        # i = idx%self.N_t
        #return self.X_Data_train[0,idx][0],self.X_Data_train[0,idx][1],self.X_Data_train[1,idx] #return the x and t values of the grid and value of X for the physics loss
        return self.grille[idx,0],self.grille[idx,1]#float(self.x[j]),float(self.t[i])      # This class only returns the x and t values of the grid not the velocity

class Train_PINN():

    def __init__(self,learning_rate,nbr_iteration,w_1,w_2,w_3,w_4):
        self.learning_rate = learning_rate
        self.nbr_iteration = nbr_iteration
        self.w_1 = w_1
        self.w_2 = w_2
        self.w_3 = w_3
        self.w_4 = w_4
        self.optimizer = torch.optim.Adam(model.parameters(),lr = self.learning_rate)
        
    def train(self):
        loss = np.zeros((self.nbr_iteration,1))
        loss_physics_tracker = np.zeros((self.nbr_iteration,1))
        loss_colocation_tracker = np.zeros((self.nbr_iteration,1))
        loss_boundary_conditions_tracker = np.zeros((self.nbr_iteration,1))
        loss_initial_conditions_tracker = np.zeros((self.nbr_iteration,1))
        for iteration in tqdm.tqdm(range(self.nbr_iteration)):
            self.optimizer.zero_grad()

            #initial conditions Loss
            # build tensor from dataset (columns: k, t, u)
            
            # initial_list = [initial_train_dataset[i] for i in range(len(initial_train_dataset))]
            # initial_rows = [[float(x), float(t), float(u)] for x,t,u in initial_list]
            initial_train_data = initial_train_dataset.tensor_data#torch.tensor(initial_rows, dtype=torch.float32)
            u_pd_ini = model(initial_train_data[:, 0:2])
            u_exa_ini = initial_train_data[:,2:3]
            loss_initital_conditions = self.w_1*torch.mean((u_pd_ini-u_exa_ini)**2)

            #Boundary conditions Loss
            # boundary_list = [boundary_train_dataset[i] for i in range(len(boundary_train_dataset))]
            # boundary_rows = [[float(x), float(t), float(u)] for x,t,u in boundary_list]
            boundary_train_data = boundary_train_dataset.tensor_data_bc#torch.tensor(boundary_rows, dtype=torch.float32)
            u_pd_bou = model(boundary_train_data[:, 0:2])
            u_exa_bou = boundary_train_data[:,2:3]
            loss_boundary_conditions = self.w_2*torch.mean((u_pd_bou-u_exa_bou)**2)


            
            colocation_train_data = colocation_dataset.tensor_data_colocation
            u_pd_colocation = model(colocation_train_data[:,0:2])
            loss_colocation = self.w_3*torch.mean((u_pd_colocation-colocation_train_data[:,2])**2)

            grid_train_data = grid_dataset.grille.requires_grad_(True)
            u_pd = model(grid_train_data)
            #a = torch.autograd.grad(u_pd, train_data, torch.ones_like(u_pd), create_graph=True)
            u_t = torch.autograd.grad(u_pd, grid_train_data, torch.ones_like(u_pd), create_graph=True)[0][:,1:2]
            # u_x = torch.autograd.grad(u_pd, train_data, torch.ones_like(u_pd), create_graph=True)[0][:,0:1]
            # u_xx = torch.autograd.grad(u_x, train_data, torch.ones_like(u_pd), create_graph=True)[0][:,0:1]
            #physics = u_t + u_pd*u_x - nu*u_xx
            # faire la somme sur les shells
            # for i in range (2,nb_shell-2):
            u_t = u_t.view(int(grid_train_data.shape[0]/(k_max-k_min)),int(k_max-k_min))
            u_pd = u_pd.view(int(grid_train_data.shape[0]/(k_max-k_min)),int(k_max-k_min))
            GOY_physics = torch.zeros(Npts,(k_max-2 - (k_min+2)))
            for i in range (k_max-2-(k_min+2)):
                GOY_physics[:,i] = u_t[:,i] -K[i]*u_pd[:,i+1]*u_pd[:,i+2] +K[i]*eps/lmb*u_pd[:,i-1]*u_pd[:,i+1] - K[i]*((eps-1)/lmb**2)*u_pd[:,i-2]*u_pd[:,i-1] + nu*K[i]*K[i]*u_pd[:,i] # à confirmer
            loss_physics = self.w_4*torch.mean(GOY_physics**2)

            #Total Loss
            total_loss = loss_initital_conditions + loss_boundary_conditions + loss_physics + loss_colocation
            total_loss.backward()
            self.optimizer.step()
            loss[iteration]=total_loss.detach().numpy()
            loss_physics_tracker[iteration] = loss_physics.detach().numpy()
            loss_colocation_tracker[iteration] = loss_colocation.detach().numpy()
            loss_boundary_conditions_tracker[iteration] = loss_boundary_conditions.detach().numpy()
            loss_initial_conditions_tracker[iteration] = loss_initital_conditions.detach().numpy()
            print(iteration)
            print(total_loss)
            
            
        return loss,loss_physics_tracker,loss_colocation_tracker,loss_boundary_conditions_tracker,loss_initial_conditions_tracker





torch.manual_seed(119)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
os.system(f'device: {device}')
os.system(f'device : {torch.cuda.get_device_name(0)}')
model = GOY_PINN(n_input=2,n_output=1,n_hidden=128,n_layers=8)
model.cuda()
#### input et output du PINN #####
# grid_test = torch.tensor([[x, t] for x in np.array([k for k in range(0,10)]) for t in np.array([t for t in range(100)])], dtype=torch.float32).requires_grad_(True)
# result = model(grid_test)



# nbr_initial_x = N_x   # N_x samples in space for the definition of the initial condition
nbr_initial_t = 1     # Only t=0 for defining the initial condition

# boundary_x = 2    # Boundary conditions of a 1d solution
# boundary_t = N_t  # Boundary conditions for any time
t_min = 0
t_max = Npts

############# initialization of dataset for training #################
initial_train_dataset = initials_variables_data(Data_ic,nbr_initial_t,k_min,k_max)
boundary_train_dataset = boundary_variables_data(X_boundary=Data_bc)
colocation_dataset = colocations_variables_data(Data_train)
grid_dataset = grid_data(k_min,k_max,t_min,t_max)

initial_train_dataset.tensor_data.cuda()
boundary_train_dataset.tensor_data_bc.cuda()
colocation_dataset.tensor_data_colocation.cuda()
grid_dataset.grille.cuda()




learning_rate,nbr_iteration,w_1,w_2,w3,w_4 = 0.005,100000,1,1,1,1
t = Train_PINN(learning_rate,nbr_iteration,w_1,w_2,w3,w_4)
Total_loss = t.train()
model.eval()

U = model(grid_dataset.grille).detach().numpy().reshape(t_max-t_min,k_max-k_min)
U_exa = Data_shell[t_min:t_max,k_min:k_max]

square_error = (U-U_exa)**2
rmse = np.sqrt(np.mean(square_error))
print("RMSE:", rmse)

plt.figure()
plt.plot(U[:,0],label='Predicted u1')
plt.plot(U_exa[:,0],label='Exact u1')
plt.plot(U[:,2],label='Predicted u2')
plt.plot(U_exa[:,2],label='Exact u2')
plt.plot(U[:,4],label='Predicted u4')
plt.plot(U_exa[:,4],label='Exact u4')
plt.plot(U[:,6],label='Predicted u6')
plt.plot(U_exa[:,6],label='Exact u6')
plt.plot(U[:,8],label='Predicted u8')
plt.plot(U_exa[:,8],label='Exact u8')
plt.xlabel('Time')
plt.ylabel('Velocity')
plt.legend()

plt.savefig("/Odyssey/private/s26calme/code_stage/prediction.png")

plt.figure()
plt.imshow(square_error,extent=[t_min,t_max,k_min,k_max])
cbar = plt.colorbar()
cbar.set_label('Square Error')
plt.xlabel('Time')
plt.ylabel('Shell Index')
plt.axis(True)
plt.savefig("/Odyssey/private/s26calme/code_stage/square_error.png")

#torch.save(model.state_dict(),'/Odyssey/private/s26calme/code_stage/')


plt.figure()
plt.plot(Total_loss[0],label='Total Loss')
plt.plot(Total_loss[1],label='Physics Loss')
plt.plot(Total_loss[2],label='Colocation Loss')
plt.plot(Total_loss[3],label='Boundary Conditions Loss')    
plt.xlabel('Iterations')
plt.ylabel('Losses')
plt.legend()
plt.savefig("/Odyssey/private/s26calme/code_stage/losses.png")
